											"{ObjDir}Error.a.o"						∂
											"{ObjDir}OSDispatch.a.o"				∂
											"{ObjDir}ProcessMgrMisc.a.o"			∂
											"{ObjDir}ZoomRect.a.o"					∂
											"{ObjDir}Switch.a.o"					∂
											"{ObjDir}Startup.c.o"					∂
											"{ObjDir}AppleEventExtensions.c.o"		∂
											"{ObjDir}Debugger.c.o"					∂
											"{ObjDir}DeskMgrPatches.c.o"			∂
											"{ObjDir}Error.c.o"						∂
											"{ObjDir}EventMgrPatches.c.o"			∂
											"{ObjDir}FileSystem.c.o"				∂
											"{ObjDir}HList.c.o"						∂
											"{ObjDir}LayerMgrPatches.c.o"			∂
											"{ObjDir}Memory.c.o"					∂
											"{ObjDir}MemoryMgrPatches.c.o"			∂
											"{ObjDir}MenuMgrPatches.c.o"			∂
											"{ObjDir}OSDispatch.c.o"				∂
											"{ObjDir}PackageMgrPatches.c.o"			∂
											"{ObjDir}Patches.c.o"					∂
											"{ObjDir}Processes.c.o"					∂
											"{ObjDir}Puppet.c.o"					∂
											"{ObjDir}Queue.c.o"						∂
											"{ObjDir}ResourceMgrPatches.c.o"		∂
											"{ObjDir}ScrapCoercion.c.o"				∂
											"{ObjDir}SegmentLoaderPatches.c.o"		∂
											"{ObjDir}Sleep.c.o"						∂
											"{ObjDir}Switch.c.o"					∂
											"{ObjDir}WindowMgrPatches.c.o"			∂
											"{IfObjDir}PMInterface.o"				∂
											"{Libraries}Runtime.o"					∂
											"{ObjDir}Data.c.o"						∂
											"{ObjDir}Eppc.c.o"						∂
											"{ObjDir}MemoryMgr24Patches.c.o"		∂
											"{ObjDir}MemoryMgr32Patches.c.o"		∂
											"{ObjDir}Schedule.c.o"					∂
											"{ObjDir}Utilities.c.o"					∂
